import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { TbCategoryPlus } from "react-icons/tb";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";
import { GrBlog, GrDashboard } from "react-icons/gr";
import DefaultLayout from "@layouts/default-layout";
import PageContent from "@components/page-content/page-content";
import { MdOutlineInventory } from "react-icons/md";
import { RiCustomerService2Fill } from "react-icons/ri";
import { FcSalesPerformance } from "react-icons/fc";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "dashboard",
                        list: "/dashboard",
                        icon: <GrDashboard />,
                      },
                      {
                        name: "blog_posts",
                        list: "/dashboard/blog-posts",
                        create: "/dashboard/blog-posts/create",
                        edit: "/dashboard/blog-posts/edit/:id",
                        show: "/dashboard/blog-posts/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <GrBlog />,
                      },
                      {
                        name: "categories",
                        list: "/dashboard/categories",
                        create: "/dashboard/categories/create",
                        edit: "/dashboard/categories/edit/:id",
                        show: "/dashboard/categories/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <TbCategoryPlus />,
                      },
                      {
                        name: "customers",
                        list: "/dashboard/customers",
                        show: "/dashboard/customers/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <RiCustomerService2Fill />,
                      },
                      {
                        name: "inventory",
                        list: "/dashboard/inventory",
                        show: "/dashboard/inventory/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <MdOutlineInventory />,
                      },
                      {
                        name: "orders",
                        list: "/dashboard/orders",
                        show: "/dashboard/orders/show/:id",
                        meta: {
                          canDelete: true,
                        },
                        icon: <FcSalesPerformance  />,
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "JVzy3N-QCyo8k-c3ejgO",
                    }}
                  >
                    <DefaultLayout>
                      <PageContent hasSider>{children}</PageContent>
                    </DefaultLayout>
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
